ocpp_path: wss://cpc.us.charge.ampeco.tech:443/poc14
logname: one
stations:
  - serial: SC001
    power: 100000
    currentType: DC
    requireAuthorize: "false"
    automatictransaction: "false"
    minDuration: 600
    maxDuration: 600
    minDelayBetweenTwoTransactions: 5
    maxDelayBetweenTwoTransactions: 5
    connectors: [ 1 ]
    rfid:
      id:
        - "TEST"
